### ISSUE TITLE
[GitHub PR Plugin] Entity page should show pull requests for that entity

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage#8]
The entity page should have a tab named "pull requests" which shows the pull requests for that specific service. It should look very similar to the `/github-pull-requests` page.

The owner and name of the repo to look up in the GitHub API can be found in the same way as the GitHub actions plugin is doing. The YAML file which describes each service has an annotation on it which stores the `owner/name` of the repo.

```js
// plugins/catalog/src/components/EntityPage/EntityPage.tsx
{entity.metadata?.annotations?.[
  'backstage.io/github-actions-id'
] && (
  <Grid item sm={3}>
    <GithubActionsWidget entity={entity} branch="master" />
  </Grid>
)}
```

For example, [here is the YAML metadata](https://github.com/RoadieHQ/sample-service/blob/master/backstage.yaml) for the `RoadieHQ/sample-service`.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  annotations:
    backstage.io/github-actions-id: RoadieHQ/sample-service
spec:
  # omitted for brevity
```

One problem we will encounter is that the tabs implementation on the Entity Page doesn't really work. This tabs implementation should be improved as needed, and contributed upstream to Backstage.
